/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedReviewRouteImport } from './routes/_authenticated/review'
import { Route as AuthenticatedUploadRouteImport } from './routes/_authenticated/upload'
import { Route as AuthenticatedCourseCourseIdRouteImport } from './routes/_authenticated/course.$courseId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/_authenticated/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedReviewRoute = AuthenticatedReviewRouteImport.update({
  id: '/_authenticated/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUploadRoute = AuthenticatedUploadRouteImport.update({
  id: '/_authenticated/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCourseCourseIdRoute =
  AuthenticatedCourseCourseIdRouteImport.update({
    id: '/_authenticated/course/$courseId',
    path: '/course/$courseId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/review': typeof AuthenticatedReviewRoute
  '/upload': typeof AuthenticatedUploadRoute
  '/course/$courseId': typeof AuthenticatedCourseCourseIdRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/review': typeof AuthenticatedReviewRoute
  '/upload': typeof AuthenticatedUploadRoute
  '/course/$courseId': typeof AuthenticatedCourseCourseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/review': typeof AuthenticatedReviewRoute
  '/_authenticated/upload': typeof AuthenticatedUploadRoute
  '/_authenticated/course/$courseId': typeof AuthenticatedCourseCourseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/auth' | '/dashboard' | '/review' | '/upload' | '/course/$courseId'
  fileRoutesByTo: FileRoutesByTo
  to: '/auth' | '/dashboard' | '/review' | '/upload' | '/course/$courseId'
  id:
    | '__root__'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/review'
    | '/_authenticated/upload'
    | '/_authenticated/course/$courseId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedReviewRoute: typeof AuthenticatedReviewRoute
  AuthenticatedUploadRoute: typeof AuthenticatedUploadRoute
  AuthenticatedCourseCourseIdRoute: typeof AuthenticatedCourseCourseIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/review': {
      id: '/_authenticated/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof AuthenticatedReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/upload': {
      id: '/_authenticated/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof AuthenticatedUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/course/$courseId': {
      id: '/_authenticated/course/$courseId'
      path: '/course/$courseId'
      fullPath: '/course/$courseId'
      preLoaderRoute: typeof AuthenticatedCourseCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedReviewRoute: AuthenticatedReviewRoute,
  AuthenticatedUploadRoute: AuthenticatedUploadRoute,
  AuthenticatedCourseCourseIdRoute: AuthenticatedCourseCourseIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
